# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfcb6a3efcf7bfe2032e6ca873803375529c25f4579209183200782d34ce10282a9ded95558b26bee11b239f3bbf0ce285fc193049007a4357000f7a13bac432

test:
  secret_key_base: 1923f0d6d7765413d21c9145c1e10b9a0193c672091d81f54d63b52bcd018612da176aabd2a52937884ed6a4ecdef2fdeb84f8826252f0fa2df4d5a17c5d096f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
